### ISSUE TITLE
TO DO item provides little detail

### ISSUE THREAD

**Issue by alfredocambera** [funkydan2/hugo-kiera#10]
Dan, I don't understand the first requirement of the TO DO list: 

- `/layout/_default/terms.html` needs some works, it functions now, barely.

How do you reproduce the referred error?

**Comment by funkydan2** [comment]
I don't know what that refers to - that's part of the original README written by @avianto. I should clean up that 'to do'...and turn them into GitHub issues if they're relevant.

**Comment by alfredocambera** [comment]
I agree. Creating GitHub issues would improve visibility and and promote collaboration.
