### ISSUE TITLE
improve social networks links handling

### ISSUE THREAD

**Issue by alfredocambera** [funkydan2/hugo-kiera#12]
Found a theme and I think it uses a very interesting approach, as it doesn't requires to clutter the main configuration file and provides a lot of flexibility. I had to go to the partials corresponding file to find out how the strings were built.

https://github.com/halogenica/beautifulhugo/blob/master/data/beautifulhugo/social.toml

What do you think?

**Comment by funkydan2** [comment]
Yeah - that's nice, and was very easy to implement.

**Comment by alfredocambera** [comment]
Great, thanks a lot Dan.
