### ISSUE TITLE
Support for Featured images

### ISSUE THREAD

**Issue by madpipeline** [funkydan2/hugo-kiera#22]
Hello,

Can you add support for featured images in the list view pages? And on the homepage?

If this support exists, I didn't find how to use it.

**Comment by funkydan2** [comment]
hi @madpipeline,

This theme doesn't support feature images, other than for [twitter cards](https://gohugo.io/templates/internal/#twitter-cards). The reason for this is the philosophy of the design to be heavily text based (see the Readme).

Adding this support would be non-trivial, but not impossible. You'd need to change the CSS to support the display of feature images, and also the template. I'd be willing to consider a PR if you're able to make these changes. Alternatively, you could look into some of the [other hugo themes](https://themes.gohugo.io) which are more graphically orientated.
