### ISSUE TITLE
Dark mode is not applied to some Markdown elements

### ISSUE THREAD

**Issue by lawhiteley** [funkydan2/hugo-kiera#26]
More specifically, blockquotes and code blocks that aren't managed by Hugo are quite difficult to read if the client has dark mode enabled on their OS. 

Can be seen by visiting the following page with dark mode enabled: https://themes.gohugo.io//theme/hugo-kiera/post/markdown-syntax/

**Comment by funkydan2** [comment]
Thanks @lawhiteley. I've had a go at choosing some more legible colours for the dark mode.
