### ISSUE TITLE
index page posts fixed 10

### ISSUE THREAD

**Issue by lau-jay** [funkydan2/hugo-kiera#32]
hi funkydan2 ，I like hugo-kiera.  I want setting index page posts.
reading code fund it's  fixed 10.
```
{{ range $index, $page := first 10 (where site.RegularPages "Section" "in" .Site.Params.mainSections) }}
```
can you give a param in config.toml?

**Comment by funkydan2** [comment]
What do you think about https://github.com/funkydan2/hugo-kiera/commit/4db667624a43640c3d1664daeb1bb80f837414fc

**Comment by lau-jay** [comment]
Thank you so much,  great job。
