### ISSUE TITLE
Code block formatting

### ISSUE THREAD

**Issue by tarquin-the-brave** [funkydan2/hugo-kiera#35]
Hi,

Love the theme! Very minimal. Four years into my career I've started trying to write a technical blog (four years too late... I know).

I don't know if this is an issue with the theme or Hugo (I'm not that familiar with front end stuff), but I'm finding code blocks a bit clunky.

* The don't wrap or allow scroll sideways
* I have to add the new lines in
* Zooming in and out some of the writing goes off the edge of the block background.
* A page the formats quite nicely through a web browser on a PC goes off the edge of the codeblock background on a mobile phone.

![Screenshot-pc](https://user-images.githubusercontent.com/30193535/76840115-8d804700-682e-11ea-9581-fc8c2de6ea1f.png)

![Screenshot-phone](https://user-images.githubusercontent.com/30193535/76839577-a50b0000-682d-11ea-9aa7-68ce29c93065.png)

I'm happy to spend some time looking into this and have a go at sending in a PR.

I was thinking instead I could embed github gists, just that means mastering the codeblocks seperately from the blog which is a bit annoying.

What would you advise?

Thanks.

**Comment by dannyBies** [comment]
Have you tried [updating the theme](https://github.com/funkydan2/hugo-kiera#update-the-theme) to the latest version. I believe some of the issues you're experiencing should have been fixed now.

**Comment by tarquin-the-brave** [comment]
Updated the theme from commit `c0467583e57abd758b2f4d97bd2038d9fab0aa50` to `b7ac2cff368999dd42292b68d1316e825af4c845` (latest).

Same problems.  On mobile the code block spills over the edge of the background and on PC, if I zoom in the same ca happen, and if I make a line in the code block longer than a certain length it does it too.

![Screenshot-phone-latest](https://user-images.githubusercontent.com/30193535/76938438-81f45500-68ee-11ea-8aec-7bd985c8bc82.jpg)

![Screenshot-pc-latest](https://user-images.githubusercontent.com/30193535/76938484-92a4cb00-68ee-11ea-96a4-6bf641cb8696.png)
