### ISSUE TITLE
Footnotes not working properly

### ISSUE THREAD

**Issue by euisuny** [funkydan2/hugo-kiera#39]
Hello, I'm using markdown footnotes with [^1] and at the end of the document with [^1] : . 
The inlined footnote unfortunately doesn't seem to get superscripted nor does it get a hyperlink to the footnote description. Is there a fix to this? Thanks!

**Comment by funkydan2** [comment]
In the [Demo Site](https://themes.gohugo.io//theme/hugo-kiera/post/markdown-syntax/) there's a page with footnotes (scroll down to the section on blockquotes). Is your site doing something different? Could you post a link to (a) an example page on your live site and (b) your site's source?

(The source of the demo page comes from the [HugoBasicExample](https://github.com/gohugoio/hugoBasicExample/blob/master/content/post/markdown-syntax.md).)

**Comment by euisuny** [comment]
Oops, there was something wrong with my formatting and this totally works. Thank you for your help!
