### ISSUE TITLE
Favicon not working

### ISSUE THREAD

**Issue by tobiaszheller** [funkydan2/hugo-kiera#4]
Hi,
I am with favicon. I have found few question on web and always the answer was:
> Add it to static folder and it will be copied into public.

It is copied into public, however favicon is not loaded. Do you know if in template reference to favicon is missing?

**Comment by funkydan2** [comment]
I've just added support.

If you have a look at `/layouts/partials/header_includes.html` the first three lines have added support for that. You'll need to put the appropriate filename in your config file.

**Comment by funkydan2** [comment]
(Can you please check it works for you, then we can close the issue.)

**Comment by tobiaszheller** [comment]
It's working now, thanks @funkydan2
