### ISSUE TITLE
Help with tags and categories.

### ISSUE THREAD

**Issue by Abhinav1217** [funkydan2/hugo-kiera#40]
Hi,
I have copied config.toml (and converted to yaml because forestry automatically created yaml before ) from your examplesite directory and uncommented the tags, and categories section of the config.

Still when I go to /tags/ or /categories/ it goes 404. I even tried to create an empty tags.md and categories.md but still didn't work. What am I doing wrong. I have no experience with hugo.

PS: Can you also tell me how to remove /post/ from url ?

**Comment by funkydan2** [comment]
Hi @Abhinav1217,

I'm happy to help with your problems, but from the sounds of it, they're not specifically *issues* with this theme, but rather problems you're having with using hugo.

I recommend you open a thread over at the [Hugo forums](https://discourse.gohugo.io/). I keep an eye on that forum, and if you open a thread with the same topic as this one, I'll chime in over there (as will a bunch of other helpful people). Before you post the thread, make sure you [read this about requesting help](https://discourse.gohugo.io/t/requesting-help/9132)...especially the bit about providing a link to your code.

Without seeing your code any help is a bit of a shot in the dark. But my guess as to why the `tags` and `categories` pages are empty is that you don't have any pages with a `tag` or `category` specified.

As to your *ps* question: you may find your answer [by reading about the slug settings in the hugo documentation](https://gohugo.io/content-management/organization/#slug).

**Comment by Abhinav1217** [comment]
Hi,
You can see the blog at https://missing-dots.in and check the [code hosted on github]( https://github.com/Abhinav1217/missing-dots ). I used Forestry.io to create initial website with some other theme, But then tried bunch of different themes from `themes.gohugo.io` , finally ended up liking your theme.

I copied the instructions from your `exampleSite/config.toml`  and used [online converter](https://toolkit.site/format.html) to convert needed part from toml to yaml . 

```
    - identifier: "tags"
      name: "Tags"
      title: "Tags"
      url: /tags/
      weight: 0
      
    - identifier: "categories"
      name: "Categories"
      title: "Categories"
      url: /categories/
      weight: 0
```

Currently there are two post on the blog all of them have few tags and categories mention. And when I click on one of the tag or categories, I can see it has generated proper link, eg, `missing-dots.in/tags/history` But the output is 404 page. 

I had already tried to follow slug settings from the same link you mentioned, Tried to create `tags.md and categories.md`, even tried `Tags.md and Categoried.md`, When it didn't work, I tried to add it to `front matter` . I am still getting 404. 

I will give it another shot today and if it doesn't work, I will post the same on the forum.

**Comment by funkydan2** [comment]
The reason Hugo isn't building pages for *tags* and *categories* is because you've disabled those taxonomies.

In the documentation it says
>While adding custom taxonomies, you need to put in the default taxonomies too, if you want to keep them.

See https://gohugo.io/content-management/taxonomies#example-adding-a-custom-taxonomy-named-series

**Comment by Abhinav1217** [comment]
Wow I missed that. author was created by previous theme. I guess I need to clean up the yaml for all then themes I am not using now. 

Thanks for the help.
