### ISSUE TITLE
Changing the Meta Description tag

### ISSUE THREAD

**Issue by darshitpp** [funkydan2/hugo-kiera#41]
I recently deployed the blog and I noticed that the description generated in the `index.html` file is `<meta name="description" content="The HTML5 Herald" />`. Was wondering if it was this theme specific as I couldn't find anything similar in the Hugo forums. 

Would appreciate if I get pointed to the relevant documentation where I could refer and change this.

**Comment by funkydan2** [comment]
Oops - that shouldn't happen. It's a simple fix which I can push later today.

**Comment by funkydan2** [comment]
Actually, it should happen **if** you haven't set `Params.description` in the config.

In `exampleSite/config.toml` it's line 29.

https://github.com/funkydan2/hugo-kiera/blob/3cc7926e90ec58f87c22b08948853beeac042dce/exampleSite/config.toml#L29

Can you check the `description` is set in your site's config file?

**Comment by darshitpp** [comment]
Okay, that works! This could have been added to the README to avoid confusion. Do you have any helpful links that I could look at to customize the theme more? (I want the links to stand out -- at the moment, they just look like plain text)

**Comment by funkydan2** [comment]
> Do you have any helpful links that I could look at to customize the theme more?

I'd recommend writing some custom CSS. If you put your CSS file in `/static`, then you can include it by setting `.Params.customCSS` in the config file.

https://github.com/funkydan2/hugo-kiera/blob/3cc7926e90ec58f87c22b08948853beeac042dce/exampleSite/config.toml#L31

**Comment by darshitpp** [comment]
Thanks! I did some custom tweaks to the theme. I also have implemented Disqus comments, but it's showing an icon like ![this](https://user-images.githubusercontent.com/7271738/84569623-bbc9e000-ada5-11ea-9866-53309987c1d0.png)

I was confused whether this is to be configured from the Disqus website or the theme as the documentation mentions there'd be a [View Document](https://github.com/funkydan2/hugo-kiera#disqus-on-demand) button.

Live site if you want: https://darshit.dev/posts/two-way-ssl-nginx/

**Comment by funkydan2** [comment]
So it should show the icon and the words 'Add/View Comments'.

The code which builds this button is in the `disqus.html` partial:
https://github.com/funkydan2/hugo-kiera/blob/3cc7926e90ec58f87c22b08948853beeac042dce/layouts/partials/disqus.html#L2

I wonder if the words aren't displayed because of the language you've got set. The theme supports english and farsi - https://github.com/funkydan2/hugo-kiera/tree/master/i18n

**Comment by darshitpp** [comment]
Yes I just cloned the theme about 2 weeks ago when I started experimenting with deploying the website. Nevertheless, I also updated the theme as per the command in the documentation: `git submodule update --rebase --remote` but I don't think there were any changes since 2 weeks

**Comment by funkydan2** [comment]
So I found a small bug in the `disqus.html` partial - just a new line in the wrong space. If you pull the latest commit the button should display the text.
