### ISSUE TITLE
Why do the the theme homepage links to the old repo?

### ISSUE THREAD

**Issue by alfredocambera** [funkydan2/hugo-kiera#49]
The [link to the homepage](https://themes.gohugo.io/hugo-kiera/) points to the old repo. I know it is the original repo but it is very confusing. 

From my point of view, this creates the following problems:

1) You are losing potential new users of the theme as people my think that the repo is not maintained. This happened to me the first time that I was looking for a theme for my blog.

2) If you look for [hugo-kiera on google](https://www.google.com/search?q=hugo-kiera) the second link goes to the old repo, and the third one to this repo. I think this may be related to the link that I referred to previously. 

Also, It would be great it that repo could be [archived](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-repositories).

What do you think?

**Comment by funkydan2** [comment]
Well spotted. I'll fix that link in a PR in a moment. It'll take a week or so for the theme's site to be updated, but that should be fixed.

As for archiving the original repo - I reckon you should open an issue over there.

**Comment by alfredocambera** [comment]
Good, I'll submit a PR to the author. Thanks a log Dan.
