### ISSUE TITLE
Links are not different with the dark theme

### ISSUE THREAD

**Issue by crazymonkyyy** [funkydan2/hugo-kiera#53]

**Comment by funkydan2** [comment]
Can you please give more information. Does [this patch](https://github.com/funkydan2/hugo-kiera/commit/de1a4afb99bfd7c399f6c28faa01aea2f72c16c2) fix anything?

**Comment by crazymonkyyy** [comment]
I ended up fixing it on my own, since I didn't want a light them at all, no idea
