### ISSUE TITLE
Configuration Question

### ISSUE THREAD

**Issue by tarquin-the-brave** [funkydan2/hugo-kiera#54]
Is there a way to get the front page to show all posts rather than only 10?

I've had a look through the readme here and the codebase but I haven't seen where that's set.

Thanks!

**Comment by funkydan2** [comment]
The number of articles per page is set by the `paginate` variable in `config.toml`

https://github.com/funkydan2/hugo-kiera/blob/ef524e6d2779156702b2e8f4c5b81651a3aebdd3/exampleSite/config.toml#L7

The easiest way to show all the posts is setting `paginate` to a sufficiently large value. Alternatively, you could override `layouts/index.html` to not use the paginator,

https://github.com/funkydan2/hugo-kiera/blob/ef524e6d2779156702b2e8f4c5b81651a3aebdd3/layouts/index.html#L5-L7

**Comment by tarquin-the-brave** [comment]
ah ha!

So I had wanged `paginate` up to `100`, but it only changed the number of posts under `/posts`.

Turns out my git submodule for kiera was on an old branch from a few months back... Git submodules tripping me up again!

Thanks for the pointers!
